name: ed25519_dart
description: Pure Dart implementation of Ed25519 - public-key signature system.
version: 1.0.2
homepage: https://github.com/semolex
author: Oleksii Semeshchuk <semolex@live.com>

environment:
  sdk: '>=2.7.0'

dependencies:
  pointycastle: ^3.0.0-nullsafety.2

dev_dependencies:
  test: any